# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
# Config schemes: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/schema.yaml
#

hub:
  config:
    JupyterHub:
      authenticator_class: nativeauthenticator.NativeAuthenticator
      admin_access: false
    Authenticator:
      admin_users:
        - user1
    NativeAuthenticator:
      enable_signup: true
      minimum_password_length: 10
      check_common_password: true
      ask_email_on_signup: false
      allow_2fa: false

proxy:
  service:
    disableHttpPort: true
  https:
    enabled: true
    type: secret
    secret:
      name: self-signed-tls
      key: tls.key
      crt: tls.crt

singleuser:
  image:
    name: jupyter/base-notebook
    tag: d39fb37995ce
  defaultUrl: "/lab"
  profileList:
    - display_name: "jupyter/base-notebook:d39fb37995ce"
      description: "very minimal Jupyter base environment"
      default: true
    - display_name: "pangeo/pangeo-notebook:2021.07.17"
      description: "provides useful Earth science data analysis packages"
      kubespawner_override:
        # since these are provided, choose "production releases" (date tags!) only
        image: pangeo/pangeo-notebook:2021.07.17

