gateway:

  backend:
    image:
      name: pangeo/pangeo-notebook
      tag: 2021.07.17
      pullPolicy: IfNotPresent
    worker:
      extraPodConfig:
        serviceAccountName: jupyterhub1-users

  extraConfig:
    clusteroptions: |
        from dask_gateway_server.options import Options, Integer, Float, String
        def option_handler(options):
            return {
                "worker_cores": options.worker_cores,
                "worker_memory": "%fG" % options.worker_memory,
            }
        c.Backend.cluster_options = Options(
            Integer("worker_cores", 1, min=1, max=4, label="Worker Cores"),
            Float("worker_memory", 1, min=1, max=16, label="Worker Memory (GiB)"),
            handler=option_handler,
        )

# Alongside JupyterHub deployment.
# https://github.com/dask/helm-chart/blob/main/daskhub/README.md

#traefik:
#  service:
#    type: ClusterIP

#
# secrets.yaml
#
# gateway:
#   auth:
#     type: jupyterhub
#     jupyterhub:
#       apiToken: ...
# #      apiUrl: ...
#