
# Alongside JupyterHub deployment. Useful resources:
# https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub
# https://github.com/pangeo-data/pangeo-cloud-federation/issues/584#issuecomment-621471832
# https://jupyterhub.readthedocs.io/en/stable/reference/services.html#properties-of-a-service
# https://github.com/dask/helm-chart/blob/main/daskhub/README.md

gateway:
  prefix: "/services/dask-gateway" # This has to match the service name specified in the JupyterHub Helm chart. Otherwise the Dask dashboard won't be reachable.
  nodeSelector:
    cloud.google.com/gke-nodepool: core-pool
  backend:
    image:
      name: pangeo/pangeo-notebook
      tag: 2021.07.17
      pullPolicy: IfNotPresent
    scheduler:
      extraPodConfig:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
    worker:
      extraPodConfig:
        serviceAccountName: jupyterhub2
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
  extraConfig:
    clusteroptions: |
        from dask_gateway_server.options import Options, Integer, Float, String
        def option_handler(options):
            return {
                "worker_cores": options.worker_cores,
                "worker_memory": "%fG" % options.worker_memory,
            }
        c.Backend.cluster_options = Options(
            Integer("worker_cores", 1, min=1, max=7, label="Worker Cores"),
            Float("worker_memory", 1, min=1, max=32, label="Worker Memory (GiB)"),
            handler=option_handler,
        )

traefik:
  service:
    type: ClusterIP
  nodeSelector:
    cloud.google.com/gke-nodepool: core-pool

controller:
  nodeSelector:
    cloud.google.com/gke-nodepool: core-pool

#
# secrets.yaml
#
# gateway:
#   auth:
#     type: jupyterhub
#     jupyterhub:
#       apiToken: "..." # $ openssl rand -hex 32
#       apiUrl: http://hub:8081/hub/api # this address is optional, if the hub is in the same namespace as Dask gateway
#
